### ISSUE TITLE
URLs that use HTTP do not show in Preview

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-web-page#105]
**How it should work** 
As a User, I can use an HTTP url in the Web Page Widget and see it in preview and on my Display.

**Comment by stulees** [comment]
This issue has been fixed with Apps PR https://github.com/Rise-Vision/rise-vision-apps/pull/949 . Validated with https://apps.risevision.com/editor/workspace/e5997229-a27a-47fa-b11b-bc350f94121d/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f in Preview and on Beta Electron Player. ChrOS player rewrites to load widget over HTTP anyway.
