### ISSUE TITLE
Web Page Widget does not allow fullscreen

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/widget-web-page#107]
### What is the expected behavior?
Web pages in Web Page Widget behave like they would in a browser if interaction is allowed.

### What is the actual behavior?
allowfullscreen appears to be set to false on the embedded page.  Some features that would be available in a browser are disabled.

### What steps can be taken to replicate the problem?
This thread on stack overflow explains the problem with a good example: https://stackoverflow.com/questions/56342001/google-maps-full-screen-not-showing-in-a-special-case

I have a more specific scenario where this is blocking a user which I will share privately.

**Comment by stulees** [comment]
@sheadarlison @PatrickA-RiseVision It's been years since working on this Widget, but to my recollection, we intentionally restricted full screen ability with Web Page widget regardless of being interactive. Presentation playlist cycle and scheduled item cycle are a couple reasons that come to mind in terms of a potential problem fullscreen could cause. Can you confirm we are changing our stance and should allow this?

**Comment by sheadarlison** [comment]
@stulees was this the reason we restricted it? https://github.com/Rise-Vision/widget-web-page/issues/60

**Comment by PatrickA-RiseVision** [comment]
@stulees given your recollection it sounds like it may be expected behavior and not a bug.  

in the case of the example that brought this up, it was working as the user expected until recently.

@sheadarlison let me know what you think.

**Comment by stulees** [comment]
@sheadarlison No that was a separate issue. 

@PatrickA-RiseVision In doing a quick scan of the codebase, we actually don't configure `allowfullscreen` on the iframe (or `allow="fullscreen"`). We haven't pushed any changes to this Widget in almost a year. 

If something changed recently, then perhaps this is due to a newer Chrome version on their player. Were they specific about this not working on their Player or in Preview?

**Comment by PatrickA-RiseVision** [comment]
@stulees I think the timing lines up with the Electron update based on his description but it's hard to be sure.

He says it isn't working on the player either.  I can confirm it doesn't work in Preview.  I can get SC to try replicating on the player.

**Comment by stulees** [comment]
@PatrickA-RiseVision I also think this is lining up with latest Electron upgrade. We'll investigate, thanks

**Comment by stulees** [comment]
@PatrickA-RiseVision This issue has now been fixed. Reboot the clients display (to ensure cache is cleared) and you should see the fullscreen button now in the embedded google maps
