### ISSUE TITLE
Website with notifications does not update until the presentation is saved and published.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-web-page#67]
**How to recreate**
1. Add the web page widget to a presentation
2. Add http://vizimodigital.com/nb/notifications.php?condo=abcd1234 to web page widget
3. Publish presentation and assign to display
4. Ask user to update website (https://app.intercom.io/a/apps/d85f4ah4/inbox/btf@risevision.com/conversations/5770413565)

**What happens**
After updating the website, the web page widget does not update, even when refresh is set to 1 minute. After saving and publishing again, the web page widget updates.

**What should happen**
Changes to notifications on this web page should be reflected within the 1 minute refresh period.

**Notes**
I have been unable to replicate this with other websites that I have created (wordpress). It seems like this is something specific to their web page setup. I would like feedback on what could be causing this, and if it is an issue with the web page widget, or their website.

**Comment by stulees** [comment]
@btfrise The Web Page Widget always creates a new iframe and loads the webpage into for a refresh. It destroys the previous one when the new one has finished loading. So there is no issue with Widget. 

If updates to the webpage aren't showing on their display running the presentation, it will likely be due to player browser adhering to what the webpage server is providing in regards to caching rules. When viewing the users webpage directly, I see a `cache-control` response header specifying max age of 48 hours. This means the browser can cache this response and reuse it for the next 48 hours. The body of the response that the server is providing is the page content you see. It would require clearing cache and refreshing browser or restarting the player to see latest changes. 

This issue can be closed.
